# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        Dialog.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.paths_list = QtWidgets.QListWidget(Dialog)
        self.paths_list.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paths_list.setStyleSheet("QListView {\n"
"    border: none;\n"
"    outline: none;\n"
"    border-radius: 10px;\n"
"       background-color: white;\n"
"       padding: 10px;\n"
"    color: #000;\n"
"}\n"
"QListView::item {\n"
"       border: none;\n"
"    border-radius: 10px;\n"
"       padding: 10px;\n"
"}\n"
"QListView::item:selected {\n"
"       border: none;\n"
"       border-radius: 10px;\n"
"       color: black;\n"
"    background-color: #1b961f;\n"
"}\n"
"QListView::item:hover {\n"
"       border: none;\n"
"       border-radius: 10px;\n"
"       color: black;\n"
"    background-color: #1b961f;\n"
"}")
        self.paths_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.paths_list.setLineWidth(1)
        self.paths_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.paths_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.paths_list.setSelectionRectVisible(False)
        self.paths_list.setObjectName("paths_list")
        self.verticalLayout_6.addWidget(self.paths_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delete_all_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_all_button.sizePolicy().hasHeightForWidth())
        self.delete_all_button.setSizePolicy(sizePolicy)
        self.delete_all_button.setMinimumSize(QtCore.QSize(150, 80))
        self.delete_all_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_all_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    padding: 0px 10px;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    background-color: #1b961f;\n"
"}\n"
"")
        self.delete_all_button.setObjectName("delete_all_button")
        self.horizontalLayout_4.addWidget(self.delete_all_button)
        self.delete_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_button.sizePolicy().hasHeightForWidth())
        self.delete_button.setSizePolicy(sizePolicy)
        self.delete_button.setMinimumSize(QtCore.QSize(150, 80))
        self.delete_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delete_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    padding: 0px 10px;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    background-color: #1b961f;\n"
"}\n"
"")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_4.addWidget(self.delete_button)
        self.start_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(150, 0))
        self.start_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    padding: 0px 10px;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    background-color:  #1b961f;\n"
"}\n"
"")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_4.addWidget(self.start_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"color: black;\n"
"font-size: 16px;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.files_line_edit = QtWidgets.QLineEdit(Dialog)
        self.files_line_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.files_line_edit.sizePolicy().hasHeightForWidth())
        self.files_line_edit.setSizePolicy(sizePolicy)
        self.files_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.files_line_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.files_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;\n"
"padding-left: 10px;\n"
"color: #000;")
        self.files_line_edit.setReadOnly(True)
        self.files_line_edit.setObjectName("files_line_edit")
        self.horizontalLayout_2.addWidget(self.files_line_edit)
        self.choose_button_1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_button_1.sizePolicy().hasHeightForWidth())
        self.choose_button_1.setSizePolicy(sizePolicy)
        self.choose_button_1.setMinimumSize(QtCore.QSize(150, 0))
        self.choose_button_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.choose_button_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"    padding: 0px 10px;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    background-color: #1b961f;\n"
"}\n"
"")
        self.choose_button_1.setObjectName("choose_button_1")
        self.horizontalLayout_2.addWidget(self.choose_button_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setStyleSheet("color: black;\n"
"font-size: 16px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.save_line_edit = QtWidgets.QLineEdit(Dialog)
        self.save_line_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_line_edit.sizePolicy().hasHeightForWidth())
        self.save_line_edit.setSizePolicy(sizePolicy)
        self.save_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.save_line_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.save_line_edit.setStyleSheet("background-color: #fff;\n"
"border-width: 0px;\n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"font-size: 14px;\n"
"padding-left: 10px;\n"
"color: #000;")
        self.save_line_edit.setReadOnly(True)
        self.save_line_edit.setObjectName("save_line_edit")
        self.horizontalLayout_3.addWidget(self.save_line_edit)
        self.choose_button_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_button_2.sizePolicy().hasHeightForWidth())
        self.choose_button_2.setSizePolicy(sizePolicy)
        self.choose_button_2.setMinimumSize(QtCore.QSize(150, 0))
        self.choose_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.choose_button_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-width: 0px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"    padding: 0px 10px;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    background-color: #1b961f;\n"
"}\n"
"")
        self.choose_button_2.setObjectName("choose_button_2")
        self.horizontalLayout_3.addWidget(self.choose_button_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.show_image_canvas = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_image_canvas.sizePolicy().hasHeightForWidth())
        self.show_image_canvas.setSizePolicy(sizePolicy)
        self.show_image_canvas.setText("")
        self.show_image_canvas.setAlignment(QtCore.Qt.AlignCenter)
        self.show_image_canvas.setOpenExternalLinks(True)
        self.show_image_canvas.setObjectName("show_image_canvas")
        self.verticalLayout_5.addWidget(self.show_image_canvas)
        self.horizontalLayout.addLayout(self.verticalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.delete_all_button.setText(_translate("Dialog", "Delete All"))
        self.delete_button.setText(_translate("Dialog", "Delete File"))
        self.start_button.setText(_translate("Dialog", "Start"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>File(s) Path:</p></body></html>"))
        self.choose_button_1.setText(_translate("Dialog", " Choose File(s) "))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Save Path:</p></body></html>"))
        self.choose_button_2.setText(_translate("Dialog", " Choose Save"))
